package com.greendao.downloader;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yaf.base.entity.BasicsDataEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BASICS_DATA_ENTITY".
*/
public class BasicsDataEntityDao extends AbstractDao<BasicsDataEntity, Void> {

    public static final String TABLENAME = "BASICS_DATA_ENTITY";

    /**
     * Properties of entity BasicsDataEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Path = new Property(0, String.class, "path", false, "PATH");
    }


    public BasicsDataEntityDao(DaoConfig config) {
        super(config);
    }
    
    public BasicsDataEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BASICS_DATA_ENTITY\" (" + //
                "\"PATH\" TEXT);"); // 0: path
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BASICS_DATA_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BasicsDataEntity entity) {
        stmt.clearBindings();
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(1, path);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BasicsDataEntity entity) {
        stmt.clearBindings();
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(1, path);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public BasicsDataEntity readEntity(Cursor cursor, int offset) {
        BasicsDataEntity entity = new BasicsDataEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // path
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BasicsDataEntity entity, int offset) {
        entity.setPath(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(BasicsDataEntity entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(BasicsDataEntity entity) {
        return null;
    }

    @Override
    public boolean hasKey(BasicsDataEntity entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
