package com.greendao.downloader;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yaf.base.entity.BasicsDataEntity;
import com.yaf.base.entity.FinalDataEntity;

import com.greendao.downloader.BasicsDataEntityDao;
import com.greendao.downloader.FinalDataEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig basicsDataEntityDaoConfig;
    private final DaoConfig finalDataEntityDaoConfig;

    private final BasicsDataEntityDao basicsDataEntityDao;
    private final FinalDataEntityDao finalDataEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        basicsDataEntityDaoConfig = daoConfigMap.get(BasicsDataEntityDao.class).clone();
        basicsDataEntityDaoConfig.initIdentityScope(type);

        finalDataEntityDaoConfig = daoConfigMap.get(FinalDataEntityDao.class).clone();
        finalDataEntityDaoConfig.initIdentityScope(type);

        basicsDataEntityDao = new BasicsDataEntityDao(basicsDataEntityDaoConfig, this);
        finalDataEntityDao = new FinalDataEntityDao(finalDataEntityDaoConfig, this);

        registerDao(BasicsDataEntity.class, basicsDataEntityDao);
        registerDao(FinalDataEntity.class, finalDataEntityDao);
    }
    
    public void clear() {
        basicsDataEntityDaoConfig.clearIdentityScope();
        finalDataEntityDaoConfig.clearIdentityScope();
    }

    public BasicsDataEntityDao getBasicsDataEntityDao() {
        return basicsDataEntityDao;
    }

    public FinalDataEntityDao getFinalDataEntityDao() {
        return finalDataEntityDao;
    }

}
